version: '3.9'

services:
  app:
    build: .
    container_name: cv-reviewer-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
