version: '3.9'

services:
  app:
    build: .
    container_name: cv-reviewer-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run main.py
